### ISSUE TITLE
More variances in variable names

### ISSUE THREAD

**Issue by TheFive** [pyparsing/plusminus#21]
Hi, 

Thanks for your great work on pyparsing and plusminus.

I am searching for a parser working on pandas Series with variables.
This looks to work out of the box with plusminus (mapping all series of a dataframe to variables)
For a 1:1 adaption it would be fine to have a different identifier definition.

As the data columns i am working (they come from external CSV) on may contain spaces i would like to define a variable as 
```
var_name = pp.QuotedString('[', endQuoteChar=']').setName("identifier")
```

which currently requires a copy and paste of your library.

Christoph

**Comment by TheFive** [comment]
Ok, while standard operators are working out of the box, other functions will have to be implemented by my own, too.

**Comment by ptmcg** [comment]
Glad to hear you found pyparsing and plusminus suitable for your project!
