### ISSUE TITLE
Refactor parsers to separate Python eval() features from standard Arithmetic features

### ISSUE THREAD

**Issue by ptmcg** [pyparsing/plusminus#6]
`plusminus` is a project of 2 minds:
 - being a safe alternative to Python `eval()`
 - implementing common arithmetic notations and operations, often using Unicode operators or notation that are not supported in Python (such as `|x|` for `abs(x)`)

These two goals should be split into separate parser classes, so that "programming-ish" concepts do not necessarily bleed over into arithmetic notations, and arithmetic expressions like `|x|` are not included in safe Python `eval()` support.

**Comment by TheOneMusic** [comment]
@ptmcg Why can't we combine both? Like why can't `|x|` be as safe as `eval(x)`?

**Comment by TheOneMusic** [comment]
@ptmcg Why can't we combine both? Like why can't `|x|` be as safe as `eval(x)`? I actually also had other ideas: for example, with operators, how is the hierarchy defined? For instance, if I want to add the `⋅` and `·` operators for multiplication or `//` operator for floor division, will the hierarchy be the same as for `*` or `/`? We could for example add a way to define the hierarchy of an operator.

I also thought about operators you define by putting a symbol on the left and on the right of an expression (like `|x|` for `abs(x)`). That way we could define `floor(x)` by: `⌊x⌋`, `ceil(x)` by: `⌈x⌉` and `round(x, 0)` by `⌊x⌉` or `⌈x⌋`, for example.

**Comment by ptmcg** [comment]
The Arithmetic Parser eval will also be "safe", but its not really an alternative to Python eval() any more.

Right now, addition of custom operators in `plusminus` is not done very well - they are just added at the highest precedence level, which is not really correct.  Adding another operator for multiplication would not really insert it in the correct precedence level. Look at the code for pyparsing's example SimpleArith.py to see how operator precedence is done in the pyparsing `infixNotation` method.

**Comment by ptmcg** [comment]
> ⌊x⌋, ceil(x) by: ⌈x⌉ and round(x, 0) by ⌊x⌉ or ⌈x⌋

Are these normal arithmetic notation? Maybe a citation of an arithmetic notation reference would be good to have in the docs, and would probably list other notations to be considered to be included.

**Comment by TheOneMusic** [comment]
I see, is there a way we could overwrite this? For example, we could define a class like this:

```python
class Precedence:
    TOP = 0
    FACTORIAL = 1
    EXP = 2
    MULDIV = 3
    PLUSMINUS = 4
    BOTTOM = 5
```

And then we could use `Precedence.MULDIV` to define `⋅` and `·` operators, for example.

**Comment by TheOneMusic** [comment]
> Are these normal arithmetic notation? Maybe a citation of an arithmetic notation reference would be good to have in the docs, and would probably list other notations to be considered to be included.

`⌊x⌋` and `⌈x⌉` are official, the two other ones may not be but they are sometimes used.

**Comment by TheOneMusic** [comment]
@ptmcg I think it might be a good idea to release version 0.5.0 to pip (there has been good changes). Also version 0.4.0 hasn’t been released yet.

**Comment by ptmcg** [comment]
I was hoping to do this refactoring as part of 0.4.0 before releasing it (I always bump the version number to X+1 after releasing X to indicate that the work currently in progress is for the next release, and in case someone does a clone of the repo to test, and then sends in questions or issues).

I got some good suggestions from the SO Python chat room on how to do the "injection" of operators into the operator chain of precedence, but the changes will be kind of drastic, so probably best to release what we have now, and I'll embark on that for 0.5.0. But once I have that, I think the Python/non-Python refactoring will go pretty well.

**Comment by TheOneMusic** [comment]
Okay thank you for the information.

**Comment by ptmcg** [comment]
I've settled on the `BaseArithmeticParser` class mostly corresponding to Python `eval()`, with these distinctions:

- `|x|` absolute value notation included
- Unicode operators included (`≠ ≤ ≥ ∈ ∉ ∩ ∪ ∧ ∨` for `!= <= >= in not-in intersection union and or`)
- C-style `condition ? true_value : false_value` ternary operator included
- support for set union, intersection, and contains test
- dict and list containers not supported

The new `ArithmeticParser` class (renamed from `BasicArithmeticParser`) adds:

- trig, algebra, and random functions
- algebra constants `π τ e φ ϕ`
- `√` square root operator (unary and binary)
- exponent operators `⁻¹ ⁰ ¹ ² ³`
- `!` factorial operator
- `°` degrees-to-radians conversion operator

The former `BasicArithmeticParser` is deprecated, as too easily confused with the `BaseArithmeticParser`. A compatibility synonym is defined for now, but this will be removed in a future release (probably 1.0).
